name: PR Verify

on:
  pull_request:
    branches:
     - develop
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    defaults:
      run:
        working-directory: ./flutter_application_1

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'

      
      - run: ls -la

      # - run: flutter doctor -v

      # - run: flutter pub get

      # - run: dart analyze --fatal-infos --fatal-warnings

      # - run: flutter build apk --debug
